# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# automatically generated by gs-pypi
# please do not edit this file
#
# Original Author: Jauhien Piatlicki <piatlicki@gmail.com>
# Purpose: support installation of python packages from PyPI repo
#
# Bugs to piatlicki@gmail.com
#
# @ECLASS: gs-pypi.eclass
#

inherit distutils-r1 g-sorcery
